server.servlet.context-path: /api
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger.html

ibm:
  mq:
    queueManager: QM1
    channel: DEV.APP.SVRCONN
    host: ibm-mq
    port: 1414
    queueName: DEV.QUEUE.1

spring:
  datasource:
    url: jdbc:h2:file:./data/h2/mqdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update